# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='oIsPay',
            field=models.IntegerField(default=0),
        ),
    ]
