# Generated by Django 2.0.3 on 2018-08-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='know_first',
            field=models.CharField(default='', max_length=200, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='what_to_learn',
            field=models.CharField(default='', max_length=200, verbose_name='收获什么'),
        ),
    ]
