# Generated by Django 2.0.3 on 2018-08-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_video_learn_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='learn_times',
        ),
        migrations.AddField(
            model_name='video',
            name='video_time',
            field=models.IntegerField(default=0, verbose_name='视频长度(分钟)'),
        ),
    ]
